# Generated by Django 3.2 on 2023-11-25 16:21

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='uploads/preview/%Y/%m')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('description', tinymce.models.HTMLField()),
                ('instructions', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
                'ordering': ['created_on'],
            },
        ),
    ]
